apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: wazuh
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: dashboard-https
      port: 443
      targetPort: 443
      nodePort: 31443
    - name: wazuh-api
      port: 55000
      targetPort: 55000
      nodePort: 31550
    - name: indexer-api
      port: 9200
      targetPort: 9200
      nodePort: 31920