apiVersion: v1
kind: Service
metadata:
  name: wazuh-smtp
  namespace: wazuh
  labels:
    app: wazuh-smtp
spec:
  selector:
    app: wazuh-smtp
  ports:
    - name: smtp
      port: 25
      targetPort: 25
  clusterIP: None